### ISSUE TITLE
Custom Sets for Cubedrafting

### ISSUE THREAD

**Issue by dtxer** [brine/mtg-octgn#103]
Hey everyone,

sorry if this is the wrong place to contact you but I haven't found another option. 

I want to make custom MTG sets for cubedrafting, so that i can load my cube as a set and have a custom landbase. Can you give me a rough Idea what I'd have to do, to add a custom set to the game definition? Specifically:

The GUIDs found in the set definitions, do they have to be registered somewhere? Is there any script to convert decks to sets or to generate sets from any other source?

Thank you for your great work!

**Comment by brine** [comment]
there are some plans to implement a custom sets feature in OCTGN, I don't know if it's feasible or not though.  Currently the game feed system has made it very difficult to maintain custom sets, as OCTGN wipes out your entire set database every time the game updates.

**Comment by brine** [comment]
there was an update a while ago that allows sets XMLs to include cards from other sets, to expand the sealed/limited booster generator.  We still don't have a proper way to add custom sets to a plugin (the current method is kinda hacky and will need to be re-applied each time a game def update is released), but technically "cube" sets can be done.  Cube in quotations cuz it's not technically an actual cube, you'd just be creating a compilation booster set which borrows card data and images from pre-existing sets.

**Comment by brine** [comment]
the rest of the ticket isn't really something I can manage on the game plugin side, if there's not already a ticket for something similar on OCTGN's issue tracker, I'd suggest posting something there.
