### ISSUE TITLE
Error while installing Games

### ISSUE THREAD

**Issue by SkyPrince** [brine/mtg-octgn#107]
Error:
![error code](https://cloud.githubusercontent.com/assets/17243881/13040372/17f006b4-d3e6-11e5-868d-6de6e65b76e5.JPG)

**Comment by SkyPrince** [comment]
i really don't know what to do sir. please help me.

**Comment by brine** [comment]
there's been  a few people with this issue, it seems that your network isn't able to connect to myget's feed service.  I'm not sure if it's a router/port issue or if the ISP is blocking it, but its something outside of OCTGN's realm

**Comment by brine** [comment]
closing this as it was discovered that the myget service no longer supports windows XP, and neither does octgn.
