### ISSUE TITLE
Bomat Courier (NEW card from Kaladesh)

### ISSUE THREAD

**Issue by renpuu** [brine/mtg-octgn#108]
Hello all !
This card has problems. I cannot exile a card underneath the courier and NOT know what the card is. I could exile into a generic exile, but then the opponent can look and so can I. Secondly manifesting doesn't work either, since I KNOW what the face down card is, but my opponent does not.

Any Advice or Solutions on this ?

**Comment by brine** [comment]
Shift-dragging the top card of your library should put it into play face-down and hidden to you

**Comment by renpuu** [comment]
OH wow, was that simple ! Cheers for that :) !
Is there any resources for a list of hotkeys ?

**Comment by brine** [comment]
most of the magic-specific ones are in the in-game documents tab
