### ISSUE TITLE
Bugs/feature requests

### ISSUE THREAD

**Issue by Wirox** [brine/mtg-octgn#110]
1. Autoscripts are messed up, activated and triggered abilities that used to be automated, now often do not work at all. Examples: Khalni Garden, Thallid Shell-Dweller.
2. Activating an ability that's not implemented in the database doesn't put a blank ability onto the stack (has that ever worked?).
3. Feature request: "Move all cards to..." for all possible zones.
4. Feature request: Allow passing even if a player has already passed priority.

**Comment by brine** [comment]
these should be cleared now.  (minus the first one but I'm pretty sure the web DB has been acting up lately and causing thie)
