### ISSUE TITLE
Gold-Forge Garrison

### ISSUE THREAD

**Issue by yugo0075** [brine/mtg-octgn#114]
There is an error in the rule text of the card [Gold-Forge Garrison]. 
The word "Creature" replaced the word "Create".

While I'm at it, thank you very much for all the time you put into OCTGN, it is much appreciated.

**Comment by brine** [comment]
That's one of the rivals of ixalan cards, correct?  I believe that the set is still running on scryfall's first draft of the card text, I'll have to run it through an update to clean up all the typos

**Comment by yugo0075** [comment]
Yes, it's from Rivals of Ixalan.
Thank you for your answer.

**Comment by brine** [comment]
Should be good now
