### ISSUE TITLE
Token sets missing images

### ISSUE THREAD

**Issue by bophaybayquay** [brine/mtg-octgn#123]
I'm currently at 497/614 images from the tokens set and it doesn't go up if  I re-download the tokens set via the plugin

**Comment by brine** [comment]
There are some tokens made by older cards that don't have token cards available for them.  Before when we did image packs, there were placeholder proxy tokens created from MTGO's art assets.  But there's no way for the image downloader plugin to find these, as they don't actually exist in paper.

I've cleaned up the tokens set to remove some of the unnecessary missing tokens, but there's still 80-ish tokens without images available that are required for the game scripting to work.  So until we get actual token images for them, they will remain missing from the plugin.
