### ISSUE TITLE
Image Downloader URL not found

### ISSUE THREAD

**Issue by HerrBockwurst** [brine/mtg-octgn#126]
Hey,

when i try to start the Image Downloader Plugin, i get this error:

System.Net.WebException: Der Remotename konnte nicht aufgelöst werden: 'www.octgngames.com'
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei MTGImageFetcher.MainWindow..ctor()
   bei MTGImageFetcher.PluginMenuItem.OnClick(IDeckBuilderPluginController con)
   bei Octgn.DeckBuilder.DeckBuilderWindow.<>c__DisplayClass25_0.<LoadPlugins>b__0(Object sender, RoutedEventArgs args) in C:\projects\octgn\octgnFX\Octgn\DeckBuilder\DeckBuilderWindow.xaml.cs:Zeile 179.

**Comment by brine** [comment]
the plugin doesn't use octgngames.com anymore so this should be dealt with.
